name: pathlib
description: Object-oriented filesystem paths
version: 1.0.0
homepage: https://github.com/jwinnie/dart-pathlib
author: Jeremy Potter <git@stormdesign.us>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.4.1

dev_dependencies:
